apiVersion: v1
kind: Service
metadata:
  name: fundamental-project-service
spec:
  selector:
    app: fundamental-project
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fundamental-project
spec:
  selector:
    matchLabels:
      app: fundamental-project
  replicas: 4
  template:
    metadata:
      labels:
        app: fundamental-project
    spec:
      containers:
      - name: fundamental-project
        image: isaaclister/fundamental-project:latest
        ports:
        - containerPort: 5000
